import collections

fpr_cols = collections.OrderedDict([
    ('Last Modified', 'object'),
    ('Study Title', 'str'),
    ('Study SWID', 'float'),
    ('Study Attributes', 'str'),
    ('Experiment Name', 'str'),
    ('Experiment SWID', 'float'),
    ('Experiment Attributes', 'str'),
    ('Root Sample Name', 'str'),
    ('Root Sample SWID', 'float'),
    ('Parent Sample Name', 'str'),
    ('Parent Sample SWID', 'float'),
    ('Parent Sample Organism IDs', 'str'),
    ('Parent Sample Attributes', 'str'),
    ('Sample Name', 'str'),
    ('Sample SWID', 'float'),
    ('Sample Organism ID', 'str'),
    ('Sample Organism Code', 'str'),
    ('Sample Attributes', 'str'),
    ('Sequencer Run Name', 'str'),
    ('Sequencer Run SWID', 'float'),
    ('Sequencer Run Attributes', 'str'),
    ('Sequencer Run Platform ID', 'str'),
    ('Sequencer Run Platform Name', 'str'),
    ('Lane Name', 'str'),
    ('Lane Number', 'str'),
    ('Lane SWID', 'float'),
    ('Lane Attributes', 'str'),
    ('IUS Tag', 'str'),
    ('IUS SWID', 'float'),
    ('IUS Attributes', 'str'),
    ('Workflow Name', 'str'),
    ('Workflow Version', 'str'),
    ('Workflow SWID', 'float'),
    ('Workflow Attributes', 'str'),
    ('Workflow Run Name', 'str'),
    ('Workflow Run Status', 'str'),
    ('Workflow Run SWID', 'float'),
    ('Workflow Run Attributes', 'str'),
    ('Workflow Run Input File SWAs', 'str'),
    ('Processing Algorithm', 'str'),
    ('Processing SWID', 'float'),
    ('Processing Attributes', 'str'),
    ('Processing Status', 'str'),
    ('File Meta-Type', 'str'),
    ('File SWID', 'float'),
    ('File Attributes', 'str'),
    ('File Path', 'str'),
    ('File Md5sum', 'str'),
    ('File Size', 'float'),
    ('File Description', 'str'),
    ('Path Skip', 'str'),
    ('Skip', 'str'),
    ('Status', 'str'),
    ('Status Reason', 'str'),
    ('LIMS IUS SWID', 'int64'),
    ('LIMS Provider', 'object'),
    ('LIMS ID', 'object'),
    ('LIMS Version', 'object'),
    ('LIMS Last Modified', 'object')])

fpr_path='/.mounts/labs/seqprodbio/private/backups/seqware_files_report_latest.tsv.gz'